// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_a_Dense_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Weights_address0,
        Weights_ce0,
        Weights_q0,
        Weights_address1,
        Weights_ce1,
        Weights_q1,
        OutGAP4_load,
        OutGAP4_load_1,
        OutGAP4_load_2,
        OutGAP4_load_3,
        OutGAP4_load_4,
        OutGAP4_load_5,
        OutGAP4_load_6,
        OutGAP4_load_7,
        OutGAP4_load_8,
        OutGAP4_load_9,
        OutGAP4_load_10,
        OutGAP4_load_11,
        OutGAP4_load_12,
        OutGAP4_load_13,
        OutGAP4_load_14,
        OutGAP4_load_15,
        OutGAP4_load_16,
        OutGAP4_load_17,
        OutGAP4_load_18,
        OutGAP4_load_19,
        OutGAP4_load_20,
        OutGAP4_load_21,
        OutGAP4_load_22,
        OutGAP4_load_23,
        OutGAP4_load_24,
        OutGAP4_load_25,
        OutGAP4_load_26,
        OutGAP4_load_27,
        OutGAP4_load_28,
        OutGAP4_load_29,
        OutGAP4_load_30,
        OutGAP4_load_31,
        OutDense0_address0,
        OutDense0_ce0,
        OutDense0_we0,
        OutDense0_d0,
        grp_fu_1453_p_din0,
        grp_fu_1453_p_din1,
        grp_fu_1453_p_opcode,
        grp_fu_1453_p_dout0,
        grp_fu_1453_p_ce,
        grp_fu_1457_p_din0,
        grp_fu_1457_p_din1,
        grp_fu_1457_p_opcode,
        grp_fu_1457_p_dout0,
        grp_fu_1457_p_ce,
        grp_fu_1461_p_din0,
        grp_fu_1461_p_din1,
        grp_fu_1461_p_dout0,
        grp_fu_1461_p_ce,
        grp_fu_1465_p_din0,
        grp_fu_1465_p_din1,
        grp_fu_1465_p_dout0,
        grp_fu_1465_p_ce,
        grp_fu_1469_p_din0,
        grp_fu_1469_p_din1,
        grp_fu_1469_p_opcode,
        grp_fu_1469_p_dout0,
        grp_fu_1469_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 17'd1;
parameter    ap_ST_fsm_pp0_stage1 = 17'd2;
parameter    ap_ST_fsm_pp0_stage2 = 17'd4;
parameter    ap_ST_fsm_pp0_stage3 = 17'd8;
parameter    ap_ST_fsm_pp0_stage4 = 17'd16;
parameter    ap_ST_fsm_pp0_stage5 = 17'd32;
parameter    ap_ST_fsm_pp0_stage6 = 17'd64;
parameter    ap_ST_fsm_pp0_stage7 = 17'd128;
parameter    ap_ST_fsm_pp0_stage8 = 17'd256;
parameter    ap_ST_fsm_pp0_stage9 = 17'd512;
parameter    ap_ST_fsm_pp0_stage10 = 17'd1024;
parameter    ap_ST_fsm_pp0_stage11 = 17'd2048;
parameter    ap_ST_fsm_pp0_stage12 = 17'd4096;
parameter    ap_ST_fsm_pp0_stage13 = 17'd8192;
parameter    ap_ST_fsm_pp0_stage14 = 17'd16384;
parameter    ap_ST_fsm_pp0_stage15 = 17'd32768;
parameter    ap_ST_fsm_pp0_stage16 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] Weights_address0;
output   Weights_ce0;
input  [31:0] Weights_q0;
output  [13:0] Weights_address1;
output   Weights_ce1;
input  [31:0] Weights_q1;
input  [31:0] OutGAP4_load;
input  [31:0] OutGAP4_load_1;
input  [31:0] OutGAP4_load_2;
input  [31:0] OutGAP4_load_3;
input  [31:0] OutGAP4_load_4;
input  [31:0] OutGAP4_load_5;
input  [31:0] OutGAP4_load_6;
input  [31:0] OutGAP4_load_7;
input  [31:0] OutGAP4_load_8;
input  [31:0] OutGAP4_load_9;
input  [31:0] OutGAP4_load_10;
input  [31:0] OutGAP4_load_11;
input  [31:0] OutGAP4_load_12;
input  [31:0] OutGAP4_load_13;
input  [31:0] OutGAP4_load_14;
input  [31:0] OutGAP4_load_15;
input  [31:0] OutGAP4_load_16;
input  [31:0] OutGAP4_load_17;
input  [31:0] OutGAP4_load_18;
input  [31:0] OutGAP4_load_19;
input  [31:0] OutGAP4_load_20;
input  [31:0] OutGAP4_load_21;
input  [31:0] OutGAP4_load_22;
input  [31:0] OutGAP4_load_23;
input  [31:0] OutGAP4_load_24;
input  [31:0] OutGAP4_load_25;
input  [31:0] OutGAP4_load_26;
input  [31:0] OutGAP4_load_27;
input  [31:0] OutGAP4_load_28;
input  [31:0] OutGAP4_load_29;
input  [31:0] OutGAP4_load_30;
input  [31:0] OutGAP4_load_31;
output  [4:0] OutDense0_address0;
output   OutDense0_ce0;
output   OutDense0_we0;
output  [31:0] OutDense0_d0;
output  [31:0] grp_fu_1453_p_din0;
output  [31:0] grp_fu_1453_p_din1;
output  [1:0] grp_fu_1453_p_opcode;
input  [31:0] grp_fu_1453_p_dout0;
output   grp_fu_1453_p_ce;
output  [31:0] grp_fu_1457_p_din0;
output  [31:0] grp_fu_1457_p_din1;
output  [1:0] grp_fu_1457_p_opcode;
input  [31:0] grp_fu_1457_p_dout0;
output   grp_fu_1457_p_ce;
output  [31:0] grp_fu_1461_p_din0;
output  [31:0] grp_fu_1461_p_din1;
input  [31:0] grp_fu_1461_p_dout0;
output   grp_fu_1461_p_ce;
output  [31:0] grp_fu_1465_p_din0;
output  [31:0] grp_fu_1465_p_din1;
input  [31:0] grp_fu_1465_p_dout0;
output   grp_fu_1465_p_ce;
output  [31:0] grp_fu_1469_p_din0;
output  [31:0] grp_fu_1469_p_din1;
output  [4:0] grp_fu_1469_p_opcode;
input  [0:0] grp_fu_1469_p_dout0;
output   grp_fu_1469_p_ce;

reg ap_idle;
reg[13:0] Weights_address0;
reg Weights_ce0;
reg[13:0] Weights_address1;
reg Weights_ce1;
reg OutDense0_ce0;
reg OutDense0_we0;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage16;
wire    ap_block_pp0_stage16_subdone;
reg   [0:0] icmp_ln3_reg_1497;
reg    ap_condition_exit_pp0_iter0_stage16;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] reg_684;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_pp0_stage8_11001;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_pp0_stage9_11001;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_pp0_stage10_11001;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_pp0_stage11_11001;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_pp0_stage12_11001;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_pp0_stage13_11001;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_pp0_stage14_11001;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_pp0_stage15_11001;
wire    ap_block_pp0_stage16_11001;
reg   [31:0] reg_688;
reg   [31:0] reg_692;
reg   [31:0] reg_697;
reg   [31:0] reg_702;
reg   [31:0] reg_707;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] reg_712;
reg   [31:0] reg_717;
reg   [31:0] reg_722;
reg   [31:0] reg_727;
reg   [4:0] i_2_reg_1488;
reg   [4:0] i_2_reg_1488_pp0_iter1_reg;
reg   [4:0] i_2_reg_1488_pp0_iter2_reg;
reg   [4:0] i_2_reg_1488_pp0_iter3_reg;
reg   [4:0] i_2_reg_1488_pp0_iter4_reg;
reg   [4:0] i_2_reg_1488_pp0_iter5_reg;
reg   [4:0] i_2_reg_1488_pp0_iter6_reg;
reg   [4:0] i_2_reg_1488_pp0_iter7_reg;
reg   [4:0] i_2_reg_1488_pp0_iter8_reg;
wire   [0:0] icmp_ln3_fu_741_p2;
reg   [0:0] icmp_ln3_reg_1497_pp0_iter1_reg;
reg   [0:0] icmp_ln3_reg_1497_pp0_iter2_reg;
reg   [0:0] icmp_ln3_reg_1497_pp0_iter3_reg;
reg   [0:0] icmp_ln3_reg_1497_pp0_iter4_reg;
reg   [0:0] icmp_ln3_reg_1497_pp0_iter5_reg;
reg   [0:0] icmp_ln3_reg_1497_pp0_iter6_reg;
reg   [0:0] icmp_ln3_reg_1497_pp0_iter7_reg;
wire   [13:0] zext_ln3_1_fu_753_p1;
reg   [13:0] zext_ln3_1_reg_1501;
reg   [13:0] zext_ln3_1_reg_1501_pp0_iter1_reg;
reg   [13:0] zext_ln3_1_reg_1501_pp0_iter2_reg;
reg   [13:0] zext_ln3_1_reg_1501_pp0_iter3_reg;
reg   [13:0] zext_ln3_1_reg_1501_pp0_iter4_reg;
reg   [13:0] zext_ln3_1_reg_1501_pp0_iter5_reg;
reg   [13:0] zext_ln3_1_reg_1501_pp0_iter6_reg;
wire   [31:0] bitcast_ln7_fu_804_p1;
wire   [31:0] bitcast_ln7_1_fu_809_p1;
wire   [31:0] bitcast_ln7_2_fu_836_p1;
wire   [31:0] bitcast_ln7_3_fu_841_p1;
reg   [31:0] mul7_i_reg_1592;
reg   [31:0] mul7_i_1_reg_1597;
wire   [31:0] bitcast_ln7_4_fu_866_p1;
wire   [31:0] bitcast_ln7_5_fu_871_p1;
reg   [31:0] mul7_i_2_reg_1622;
reg   [31:0] mul7_i_3_reg_1627;
wire   [31:0] bitcast_ln7_6_fu_896_p1;
wire   [31:0] bitcast_ln7_7_fu_901_p1;
reg   [31:0] mul7_i_4_reg_1652;
reg   [31:0] mul7_i_5_reg_1657;
reg   [31:0] mul7_i_5_reg_1657_pp0_iter1_reg;
wire   [31:0] bitcast_ln7_8_fu_926_p1;
wire   [31:0] bitcast_ln7_9_fu_931_p1;
reg   [31:0] mul7_i_6_reg_1682;
reg   [31:0] mul7_i_6_reg_1682_pp0_iter1_reg;
reg   [31:0] mul7_i_7_reg_1687;
reg   [31:0] mul7_i_7_reg_1687_pp0_iter1_reg;
wire   [31:0] bitcast_ln7_10_fu_958_p1;
wire   [31:0] bitcast_ln7_11_fu_963_p1;
reg   [31:0] mul7_i_8_reg_1712;
reg   [31:0] mul7_i_8_reg_1712_pp0_iter1_reg;
reg   [31:0] mul7_i_9_reg_1717;
reg   [31:0] mul7_i_9_reg_1717_pp0_iter1_reg;
wire   [31:0] bitcast_ln7_12_fu_988_p1;
wire   [31:0] bitcast_ln7_13_fu_993_p1;
reg   [31:0] mul7_i_s_reg_1742;
reg   [31:0] mul7_i_s_reg_1742_pp0_iter1_reg;
reg   [31:0] mul7_i_s_reg_1742_pp0_iter2_reg;
reg   [31:0] mul7_i_10_reg_1747;
reg   [31:0] mul7_i_10_reg_1747_pp0_iter1_reg;
reg   [31:0] mul7_i_10_reg_1747_pp0_iter2_reg;
wire   [31:0] bitcast_ln7_14_fu_1018_p1;
wire   [31:0] bitcast_ln7_15_fu_1023_p1;
reg   [31:0] mul7_i_11_reg_1772;
reg   [31:0] mul7_i_11_reg_1772_pp0_iter1_reg;
reg   [31:0] mul7_i_11_reg_1772_pp0_iter2_reg;
reg   [31:0] mul7_i_12_reg_1777;
reg   [31:0] mul7_i_12_reg_1777_pp0_iter1_reg;
reg   [31:0] mul7_i_12_reg_1777_pp0_iter2_reg;
wire   [31:0] bitcast_ln7_16_fu_1048_p1;
wire   [31:0] bitcast_ln7_17_fu_1053_p1;
reg   [31:0] mul7_i_13_reg_1802;
reg   [31:0] mul7_i_13_reg_1802_pp0_iter1_reg;
reg   [31:0] mul7_i_13_reg_1802_pp0_iter2_reg;
reg   [31:0] mul7_i_14_reg_1807;
reg   [31:0] mul7_i_14_reg_1807_pp0_iter1_reg;
reg   [31:0] mul7_i_14_reg_1807_pp0_iter2_reg;
reg   [31:0] mul7_i_14_reg_1807_pp0_iter3_reg;
wire   [31:0] bitcast_ln7_18_fu_1080_p1;
wire   [31:0] bitcast_ln7_19_fu_1085_p1;
reg   [31:0] mul7_i_15_reg_1832;
reg   [31:0] mul7_i_15_reg_1832_pp0_iter1_reg;
reg   [31:0] mul7_i_15_reg_1832_pp0_iter2_reg;
reg   [31:0] mul7_i_15_reg_1832_pp0_iter3_reg;
reg   [31:0] mul7_i_16_reg_1837;
reg   [31:0] mul7_i_16_reg_1837_pp0_iter1_reg;
reg   [31:0] mul7_i_16_reg_1837_pp0_iter2_reg;
reg   [31:0] mul7_i_16_reg_1837_pp0_iter3_reg;
wire   [31:0] bitcast_ln7_20_fu_1110_p1;
wire   [31:0] bitcast_ln7_21_fu_1115_p1;
reg   [31:0] mul7_i_17_reg_1862;
reg   [31:0] mul7_i_17_reg_1862_pp0_iter1_reg;
reg   [31:0] mul7_i_17_reg_1862_pp0_iter2_reg;
reg   [31:0] mul7_i_17_reg_1862_pp0_iter3_reg;
reg   [31:0] mul7_i_18_reg_1867;
reg   [31:0] mul7_i_18_reg_1867_pp0_iter1_reg;
reg   [31:0] mul7_i_18_reg_1867_pp0_iter2_reg;
reg   [31:0] mul7_i_18_reg_1867_pp0_iter3_reg;
wire   [31:0] bitcast_ln7_22_fu_1140_p1;
wire   [31:0] bitcast_ln7_23_fu_1145_p1;
reg   [31:0] mul7_i_19_reg_1892;
reg   [31:0] mul7_i_19_reg_1892_pp0_iter1_reg;
reg   [31:0] mul7_i_19_reg_1892_pp0_iter2_reg;
reg   [31:0] mul7_i_19_reg_1892_pp0_iter3_reg;
reg   [31:0] mul7_i_19_reg_1892_pp0_iter4_reg;
reg   [31:0] mul7_i_20_reg_1897;
reg   [31:0] mul7_i_20_reg_1897_pp0_iter1_reg;
reg   [31:0] mul7_i_20_reg_1897_pp0_iter2_reg;
reg   [31:0] mul7_i_20_reg_1897_pp0_iter3_reg;
reg   [31:0] mul7_i_20_reg_1897_pp0_iter4_reg;
wire   [31:0] bitcast_ln7_24_fu_1170_p1;
wire   [31:0] bitcast_ln7_25_fu_1175_p1;
reg   [31:0] mul7_i_21_reg_1922;
reg   [31:0] mul7_i_21_reg_1922_pp0_iter1_reg;
reg   [31:0] mul7_i_21_reg_1922_pp0_iter2_reg;
reg   [31:0] mul7_i_21_reg_1922_pp0_iter3_reg;
reg   [31:0] mul7_i_21_reg_1922_pp0_iter4_reg;
reg   [31:0] mul7_i_22_reg_1927;
reg   [31:0] mul7_i_22_reg_1927_pp0_iter1_reg;
reg   [31:0] mul7_i_22_reg_1927_pp0_iter2_reg;
reg   [31:0] mul7_i_22_reg_1927_pp0_iter3_reg;
reg   [31:0] mul7_i_22_reg_1927_pp0_iter4_reg;
wire   [31:0] bitcast_ln7_26_fu_1202_p1;
wire   [31:0] bitcast_ln7_27_fu_1207_p1;
reg   [31:0] mul7_i_23_reg_1952;
reg   [31:0] mul7_i_23_reg_1952_pp0_iter1_reg;
reg   [31:0] mul7_i_23_reg_1952_pp0_iter2_reg;
reg   [31:0] mul7_i_23_reg_1952_pp0_iter3_reg;
reg   [31:0] mul7_i_23_reg_1952_pp0_iter4_reg;
reg   [31:0] mul7_i_24_reg_1957;
reg   [31:0] mul7_i_24_reg_1957_pp0_iter1_reg;
reg   [31:0] mul7_i_24_reg_1957_pp0_iter2_reg;
reg   [31:0] mul7_i_24_reg_1957_pp0_iter3_reg;
reg   [31:0] mul7_i_24_reg_1957_pp0_iter4_reg;
reg   [31:0] mul7_i_24_reg_1957_pp0_iter5_reg;
wire   [31:0] bitcast_ln7_28_fu_1232_p1;
wire   [31:0] bitcast_ln7_29_fu_1237_p1;
reg   [31:0] mul7_i_25_reg_1972;
reg   [31:0] mul7_i_25_reg_1972_pp0_iter2_reg;
reg   [31:0] mul7_i_25_reg_1972_pp0_iter3_reg;
reg   [31:0] mul7_i_25_reg_1972_pp0_iter4_reg;
reg   [31:0] mul7_i_25_reg_1972_pp0_iter5_reg;
reg   [31:0] mul7_i_25_reg_1972_pp0_iter6_reg;
reg   [31:0] mul7_i_26_reg_1977;
reg   [31:0] mul7_i_26_reg_1977_pp0_iter2_reg;
reg   [31:0] mul7_i_26_reg_1977_pp0_iter3_reg;
reg   [31:0] mul7_i_26_reg_1977_pp0_iter4_reg;
reg   [31:0] mul7_i_26_reg_1977_pp0_iter5_reg;
reg   [31:0] mul7_i_26_reg_1977_pp0_iter6_reg;
wire   [31:0] bitcast_ln7_30_fu_1242_p1;
wire   [31:0] bitcast_ln7_31_fu_1247_p1;
reg   [31:0] mul7_i_27_reg_1992;
reg   [31:0] mul7_i_27_reg_1992_pp0_iter2_reg;
reg   [31:0] mul7_i_27_reg_1992_pp0_iter3_reg;
reg   [31:0] mul7_i_27_reg_1992_pp0_iter4_reg;
reg   [31:0] mul7_i_27_reg_1992_pp0_iter5_reg;
reg   [31:0] mul7_i_27_reg_1992_pp0_iter6_reg;
reg   [31:0] mul7_i_28_reg_1997;
reg   [31:0] mul7_i_28_reg_1997_pp0_iter2_reg;
reg   [31:0] mul7_i_28_reg_1997_pp0_iter3_reg;
reg   [31:0] mul7_i_28_reg_1997_pp0_iter4_reg;
reg   [31:0] mul7_i_28_reg_1997_pp0_iter5_reg;
reg   [31:0] mul7_i_28_reg_1997_pp0_iter6_reg;
reg   [31:0] mul7_i_28_reg_1997_pp0_iter7_reg;
reg   [31:0] mul7_i_29_reg_2002;
reg   [31:0] mul7_i_29_reg_2002_pp0_iter2_reg;
reg   [31:0] mul7_i_29_reg_2002_pp0_iter3_reg;
reg   [31:0] mul7_i_29_reg_2002_pp0_iter4_reg;
reg   [31:0] mul7_i_29_reg_2002_pp0_iter5_reg;
reg   [31:0] mul7_i_29_reg_2002_pp0_iter6_reg;
reg   [31:0] mul7_i_29_reg_2002_pp0_iter7_reg;
reg   [31:0] mul7_i_30_reg_2007;
reg   [31:0] mul7_i_30_reg_2007_pp0_iter2_reg;
reg   [31:0] mul7_i_30_reg_2007_pp0_iter3_reg;
reg   [31:0] mul7_i_30_reg_2007_pp0_iter4_reg;
reg   [31:0] mul7_i_30_reg_2007_pp0_iter5_reg;
reg   [31:0] mul7_i_30_reg_2007_pp0_iter6_reg;
reg   [31:0] mul7_i_30_reg_2007_pp0_iter7_reg;
reg   [31:0] s_35_reg_2012;
reg   [31:0] Weights_load_52_reg_2022;
wire   [31:0] bitcast_ln9_fu_1262_p1;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage2_subdone;
wire   [63:0] zext_ln7_fu_763_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln7_1_fu_774_p1;
wire   [63:0] zext_ln7_2_fu_789_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln7_3_fu_799_p1;
wire   [63:0] zext_ln7_4_fu_819_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln7_5_fu_831_p1;
wire   [63:0] zext_ln7_6_fu_851_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln7_7_fu_861_p1;
wire   [63:0] zext_ln7_8_fu_881_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln7_9_fu_891_p1;
wire   [63:0] zext_ln7_10_fu_911_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln7_11_fu_921_p1;
wire   [63:0] zext_ln7_12_fu_941_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln7_13_fu_953_p1;
wire   [63:0] zext_ln7_14_fu_973_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln7_15_fu_983_p1;
wire   [63:0] zext_ln7_16_fu_1003_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln7_17_fu_1013_p1;
wire   [63:0] zext_ln7_18_fu_1033_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln7_19_fu_1043_p1;
wire   [63:0] zext_ln7_20_fu_1063_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln7_21_fu_1075_p1;
wire   [63:0] zext_ln7_22_fu_1095_p1;
wire    ap_block_pp0_stage11;
wire   [63:0] zext_ln7_23_fu_1105_p1;
wire   [63:0] zext_ln7_24_fu_1125_p1;
wire    ap_block_pp0_stage12;
wire   [63:0] zext_ln7_25_fu_1135_p1;
wire   [63:0] zext_ln7_26_fu_1155_p1;
wire    ap_block_pp0_stage13;
wire   [63:0] zext_ln7_27_fu_1165_p1;
wire   [63:0] zext_ln7_28_fu_1185_p1;
wire    ap_block_pp0_stage14;
wire   [63:0] zext_ln7_29_fu_1197_p1;
wire   [63:0] zext_ln7_30_fu_1217_p1;
wire    ap_block_pp0_stage15;
wire   [63:0] zext_ln7_31_fu_1227_p1;
wire   [63:0] zext_ln9_fu_1257_p1;
wire    ap_block_pp0_stage16;
wire   [63:0] zext_ln3_fu_1266_p1;
reg   [4:0] i_fu_180;
wire   [4:0] add_ln3_fu_747_p2;
wire    ap_loop_init;
reg   [4:0] ap_sig_allocacmp_i_2;
reg   [31:0] grp_fu_662_p0;
reg   [31:0] grp_fu_662_p1;
reg   [31:0] grp_fu_667_p0;
reg   [31:0] grp_fu_667_p1;
reg   [31:0] grp_fu_671_p0;
reg   [31:0] grp_fu_671_p1;
reg   [31:0] grp_fu_675_p0;
reg   [31:0] grp_fu_675_p1;
wire   [13:0] add_ln7_fu_757_p2;
wire   [13:0] add_ln7_1_fu_768_p2;
wire   [13:0] add_ln7_2_fu_784_p2;
wire   [13:0] add_ln7_3_fu_794_p2;
wire   [13:0] add_ln7_4_fu_814_p2;
wire   [13:0] zext_ln7_5_cast_fu_824_p3;
wire   [13:0] add_ln7_5_fu_846_p2;
wire   [13:0] add_ln7_6_fu_856_p2;
wire   [13:0] add_ln7_7_fu_876_p2;
wire   [13:0] add_ln7_8_fu_886_p2;
wire   [13:0] add_ln7_9_fu_906_p2;
wire   [13:0] add_ln7_10_fu_916_p2;
wire   [13:0] add_ln7_11_fu_936_p2;
wire   [13:0] zext_ln7_13_cast_fu_946_p3;
wire   [13:0] add_ln7_12_fu_968_p2;
wire   [13:0] add_ln7_13_fu_978_p2;
wire   [13:0] add_ln7_14_fu_998_p2;
wire   [13:0] add_ln7_15_fu_1008_p2;
wire   [13:0] add_ln7_16_fu_1028_p2;
wire   [13:0] add_ln7_17_fu_1038_p2;
wire   [13:0] add_ln7_18_fu_1058_p2;
wire   [13:0] zext_ln7_21_cast_fu_1068_p3;
wire   [13:0] add_ln7_19_fu_1090_p2;
wire   [13:0] add_ln7_20_fu_1100_p2;
wire   [13:0] add_ln7_21_fu_1120_p2;
wire   [13:0] add_ln7_22_fu_1130_p2;
wire   [13:0] add_ln7_23_fu_1150_p2;
wire   [13:0] add_ln7_24_fu_1160_p2;
wire   [13:0] add_ln7_25_fu_1180_p2;
wire   [13:0] zext_ln7_29_cast_fu_1190_p3;
wire   [13:0] add_ln7_26_fu_1212_p2;
wire   [13:0] add_ln7_27_fu_1222_p2;
wire   [13:0] add_ln9_fu_1252_p2;
wire   [31:0] bitcast_ln9_1_fu_1270_p1;
wire   [7:0] tmp_s_fu_1274_p4;
wire   [22:0] trunc_ln9_fu_1284_p1;
wire   [0:0] icmp_ln9_1_fu_1294_p2;
wire   [0:0] icmp_ln9_fu_1288_p2;
wire   [0:0] or_ln9_fu_1300_p2;
wire   [0:0] and_ln9_fu_1306_p2;
wire    ap_block_pp0_stage1_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter7_stage2;
reg    ap_idle_pp0_0to6;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [16:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to8;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
wire    ap_block_pp0_stage15_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage5_00001;
wire    ap_block_pp0_stage9_00001;
wire    ap_block_pp0_stage13_00001;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage4_00001;
wire    ap_block_pp0_stage8_00001;
wire    ap_block_pp0_stage12_00001;
wire    ap_block_pp0_stage16_00001;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage7_00001;
wire    ap_block_pp0_stage11_00001;
wire    ap_block_pp0_stage15_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage6_00001;
wire    ap_block_pp0_stage10_00001;
wire    ap_block_pp0_stage14_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_180 = 5'd0;
#0 ap_done_reg = 1'b0;
end

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage16),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage16)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            ap_enable_reg_pp0_iter8 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage16_subdone) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln3_fu_741_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_180 <= add_ln3_fu_747_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_180 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Weights_load_52_reg_2022 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_1488 <= ap_sig_allocacmp_i_2;
        i_2_reg_1488_pp0_iter1_reg <= i_2_reg_1488;
        i_2_reg_1488_pp0_iter2_reg <= i_2_reg_1488_pp0_iter1_reg;
        i_2_reg_1488_pp0_iter3_reg <= i_2_reg_1488_pp0_iter2_reg;
        i_2_reg_1488_pp0_iter4_reg <= i_2_reg_1488_pp0_iter3_reg;
        i_2_reg_1488_pp0_iter5_reg <= i_2_reg_1488_pp0_iter4_reg;
        i_2_reg_1488_pp0_iter6_reg <= i_2_reg_1488_pp0_iter5_reg;
        i_2_reg_1488_pp0_iter7_reg <= i_2_reg_1488_pp0_iter6_reg;
        i_2_reg_1488_pp0_iter8_reg <= i_2_reg_1488_pp0_iter7_reg;
        icmp_ln3_reg_1497 <= icmp_ln3_fu_741_p2;
        icmp_ln3_reg_1497_pp0_iter1_reg <= icmp_ln3_reg_1497;
        icmp_ln3_reg_1497_pp0_iter2_reg <= icmp_ln3_reg_1497_pp0_iter1_reg;
        icmp_ln3_reg_1497_pp0_iter3_reg <= icmp_ln3_reg_1497_pp0_iter2_reg;
        icmp_ln3_reg_1497_pp0_iter4_reg <= icmp_ln3_reg_1497_pp0_iter3_reg;
        icmp_ln3_reg_1497_pp0_iter5_reg <= icmp_ln3_reg_1497_pp0_iter4_reg;
        icmp_ln3_reg_1497_pp0_iter6_reg <= icmp_ln3_reg_1497_pp0_iter5_reg;
        icmp_ln3_reg_1497_pp0_iter7_reg <= icmp_ln3_reg_1497_pp0_iter6_reg;
        mul7_i_25_reg_1972_pp0_iter2_reg <= mul7_i_25_reg_1972;
        mul7_i_25_reg_1972_pp0_iter3_reg <= mul7_i_25_reg_1972_pp0_iter2_reg;
        mul7_i_25_reg_1972_pp0_iter4_reg <= mul7_i_25_reg_1972_pp0_iter3_reg;
        mul7_i_25_reg_1972_pp0_iter5_reg <= mul7_i_25_reg_1972_pp0_iter4_reg;
        mul7_i_25_reg_1972_pp0_iter6_reg <= mul7_i_25_reg_1972_pp0_iter5_reg;
        mul7_i_26_reg_1977_pp0_iter2_reg <= mul7_i_26_reg_1977;
        mul7_i_26_reg_1977_pp0_iter3_reg <= mul7_i_26_reg_1977_pp0_iter2_reg;
        mul7_i_26_reg_1977_pp0_iter4_reg <= mul7_i_26_reg_1977_pp0_iter3_reg;
        mul7_i_26_reg_1977_pp0_iter5_reg <= mul7_i_26_reg_1977_pp0_iter4_reg;
        mul7_i_26_reg_1977_pp0_iter6_reg <= mul7_i_26_reg_1977_pp0_iter5_reg;
        zext_ln3_1_reg_1501[4 : 0] <= zext_ln3_1_fu_753_p1[4 : 0];
        zext_ln3_1_reg_1501_pp0_iter1_reg[4 : 0] <= zext_ln3_1_reg_1501[4 : 0];
        zext_ln3_1_reg_1501_pp0_iter2_reg[4 : 0] <= zext_ln3_1_reg_1501_pp0_iter1_reg[4 : 0];
        zext_ln3_1_reg_1501_pp0_iter3_reg[4 : 0] <= zext_ln3_1_reg_1501_pp0_iter2_reg[4 : 0];
        zext_ln3_1_reg_1501_pp0_iter4_reg[4 : 0] <= zext_ln3_1_reg_1501_pp0_iter3_reg[4 : 0];
        zext_ln3_1_reg_1501_pp0_iter5_reg[4 : 0] <= zext_ln3_1_reg_1501_pp0_iter4_reg[4 : 0];
        zext_ln3_1_reg_1501_pp0_iter6_reg[4 : 0] <= zext_ln3_1_reg_1501_pp0_iter5_reg[4 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        mul7_i_10_reg_1747 <= grp_fu_1465_p_dout0;
        mul7_i_s_reg_1742 <= grp_fu_1461_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        mul7_i_10_reg_1747_pp0_iter1_reg <= mul7_i_10_reg_1747;
        mul7_i_10_reg_1747_pp0_iter2_reg <= mul7_i_10_reg_1747_pp0_iter1_reg;
        mul7_i_s_reg_1742_pp0_iter1_reg <= mul7_i_s_reg_1742;
        mul7_i_s_reg_1742_pp0_iter2_reg <= mul7_i_s_reg_1742_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        mul7_i_11_reg_1772 <= grp_fu_1461_p_dout0;
        mul7_i_12_reg_1777 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        mul7_i_11_reg_1772_pp0_iter1_reg <= mul7_i_11_reg_1772;
        mul7_i_11_reg_1772_pp0_iter2_reg <= mul7_i_11_reg_1772_pp0_iter1_reg;
        mul7_i_12_reg_1777_pp0_iter1_reg <= mul7_i_12_reg_1777;
        mul7_i_12_reg_1777_pp0_iter2_reg <= mul7_i_12_reg_1777_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        mul7_i_13_reg_1802 <= grp_fu_1461_p_dout0;
        mul7_i_14_reg_1807 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        mul7_i_13_reg_1802_pp0_iter1_reg <= mul7_i_13_reg_1802;
        mul7_i_13_reg_1802_pp0_iter2_reg <= mul7_i_13_reg_1802_pp0_iter1_reg;
        mul7_i_14_reg_1807_pp0_iter1_reg <= mul7_i_14_reg_1807;
        mul7_i_14_reg_1807_pp0_iter2_reg <= mul7_i_14_reg_1807_pp0_iter1_reg;
        mul7_i_14_reg_1807_pp0_iter3_reg <= mul7_i_14_reg_1807_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        mul7_i_15_reg_1832 <= grp_fu_1461_p_dout0;
        mul7_i_16_reg_1837 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        mul7_i_15_reg_1832_pp0_iter1_reg <= mul7_i_15_reg_1832;
        mul7_i_15_reg_1832_pp0_iter2_reg <= mul7_i_15_reg_1832_pp0_iter1_reg;
        mul7_i_15_reg_1832_pp0_iter3_reg <= mul7_i_15_reg_1832_pp0_iter2_reg;
        mul7_i_16_reg_1837_pp0_iter1_reg <= mul7_i_16_reg_1837;
        mul7_i_16_reg_1837_pp0_iter2_reg <= mul7_i_16_reg_1837_pp0_iter1_reg;
        mul7_i_16_reg_1837_pp0_iter3_reg <= mul7_i_16_reg_1837_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        mul7_i_17_reg_1862 <= grp_fu_1461_p_dout0;
        mul7_i_18_reg_1867 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage13_11001) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        mul7_i_17_reg_1862_pp0_iter1_reg <= mul7_i_17_reg_1862;
        mul7_i_17_reg_1862_pp0_iter2_reg <= mul7_i_17_reg_1862_pp0_iter1_reg;
        mul7_i_17_reg_1862_pp0_iter3_reg <= mul7_i_17_reg_1862_pp0_iter2_reg;
        mul7_i_18_reg_1867_pp0_iter1_reg <= mul7_i_18_reg_1867;
        mul7_i_18_reg_1867_pp0_iter2_reg <= mul7_i_18_reg_1867_pp0_iter1_reg;
        mul7_i_18_reg_1867_pp0_iter3_reg <= mul7_i_18_reg_1867_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        mul7_i_19_reg_1892 <= grp_fu_1461_p_dout0;
        mul7_i_20_reg_1897 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage14_11001) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        mul7_i_19_reg_1892_pp0_iter1_reg <= mul7_i_19_reg_1892;
        mul7_i_19_reg_1892_pp0_iter2_reg <= mul7_i_19_reg_1892_pp0_iter1_reg;
        mul7_i_19_reg_1892_pp0_iter3_reg <= mul7_i_19_reg_1892_pp0_iter2_reg;
        mul7_i_19_reg_1892_pp0_iter4_reg <= mul7_i_19_reg_1892_pp0_iter3_reg;
        mul7_i_20_reg_1897_pp0_iter1_reg <= mul7_i_20_reg_1897;
        mul7_i_20_reg_1897_pp0_iter2_reg <= mul7_i_20_reg_1897_pp0_iter1_reg;
        mul7_i_20_reg_1897_pp0_iter3_reg <= mul7_i_20_reg_1897_pp0_iter2_reg;
        mul7_i_20_reg_1897_pp0_iter4_reg <= mul7_i_20_reg_1897_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul7_i_1_reg_1597 <= grp_fu_1465_p_dout0;
        mul7_i_reg_1592 <= grp_fu_1461_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        mul7_i_21_reg_1922 <= grp_fu_1461_p_dout0;
        mul7_i_22_reg_1927 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage15_11001) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        mul7_i_21_reg_1922_pp0_iter1_reg <= mul7_i_21_reg_1922;
        mul7_i_21_reg_1922_pp0_iter2_reg <= mul7_i_21_reg_1922_pp0_iter1_reg;
        mul7_i_21_reg_1922_pp0_iter3_reg <= mul7_i_21_reg_1922_pp0_iter2_reg;
        mul7_i_21_reg_1922_pp0_iter4_reg <= mul7_i_21_reg_1922_pp0_iter3_reg;
        mul7_i_22_reg_1927_pp0_iter1_reg <= mul7_i_22_reg_1927;
        mul7_i_22_reg_1927_pp0_iter2_reg <= mul7_i_22_reg_1927_pp0_iter1_reg;
        mul7_i_22_reg_1927_pp0_iter3_reg <= mul7_i_22_reg_1927_pp0_iter2_reg;
        mul7_i_22_reg_1927_pp0_iter4_reg <= mul7_i_22_reg_1927_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        mul7_i_23_reg_1952 <= grp_fu_1461_p_dout0;
        mul7_i_24_reg_1957 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage16_11001) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        mul7_i_23_reg_1952_pp0_iter1_reg <= mul7_i_23_reg_1952;
        mul7_i_23_reg_1952_pp0_iter2_reg <= mul7_i_23_reg_1952_pp0_iter1_reg;
        mul7_i_23_reg_1952_pp0_iter3_reg <= mul7_i_23_reg_1952_pp0_iter2_reg;
        mul7_i_23_reg_1952_pp0_iter4_reg <= mul7_i_23_reg_1952_pp0_iter3_reg;
        mul7_i_24_reg_1957_pp0_iter1_reg <= mul7_i_24_reg_1957;
        mul7_i_24_reg_1957_pp0_iter2_reg <= mul7_i_24_reg_1957_pp0_iter1_reg;
        mul7_i_24_reg_1957_pp0_iter3_reg <= mul7_i_24_reg_1957_pp0_iter2_reg;
        mul7_i_24_reg_1957_pp0_iter4_reg <= mul7_i_24_reg_1957_pp0_iter3_reg;
        mul7_i_24_reg_1957_pp0_iter5_reg <= mul7_i_24_reg_1957_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul7_i_25_reg_1972 <= grp_fu_1461_p_dout0;
        mul7_i_26_reg_1977 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul7_i_27_reg_1992 <= grp_fu_1461_p_dout0;
        mul7_i_28_reg_1997 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul7_i_27_reg_1992_pp0_iter2_reg <= mul7_i_27_reg_1992;
        mul7_i_27_reg_1992_pp0_iter3_reg <= mul7_i_27_reg_1992_pp0_iter2_reg;
        mul7_i_27_reg_1992_pp0_iter4_reg <= mul7_i_27_reg_1992_pp0_iter3_reg;
        mul7_i_27_reg_1992_pp0_iter5_reg <= mul7_i_27_reg_1992_pp0_iter4_reg;
        mul7_i_27_reg_1992_pp0_iter6_reg <= mul7_i_27_reg_1992_pp0_iter5_reg;
        mul7_i_28_reg_1997_pp0_iter2_reg <= mul7_i_28_reg_1997;
        mul7_i_28_reg_1997_pp0_iter3_reg <= mul7_i_28_reg_1997_pp0_iter2_reg;
        mul7_i_28_reg_1997_pp0_iter4_reg <= mul7_i_28_reg_1997_pp0_iter3_reg;
        mul7_i_28_reg_1997_pp0_iter5_reg <= mul7_i_28_reg_1997_pp0_iter4_reg;
        mul7_i_28_reg_1997_pp0_iter6_reg <= mul7_i_28_reg_1997_pp0_iter5_reg;
        mul7_i_28_reg_1997_pp0_iter7_reg <= mul7_i_28_reg_1997_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul7_i_29_reg_2002 <= grp_fu_1461_p_dout0;
        mul7_i_30_reg_2007 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul7_i_29_reg_2002_pp0_iter2_reg <= mul7_i_29_reg_2002;
        mul7_i_29_reg_2002_pp0_iter3_reg <= mul7_i_29_reg_2002_pp0_iter2_reg;
        mul7_i_29_reg_2002_pp0_iter4_reg <= mul7_i_29_reg_2002_pp0_iter3_reg;
        mul7_i_29_reg_2002_pp0_iter5_reg <= mul7_i_29_reg_2002_pp0_iter4_reg;
        mul7_i_29_reg_2002_pp0_iter6_reg <= mul7_i_29_reg_2002_pp0_iter5_reg;
        mul7_i_29_reg_2002_pp0_iter7_reg <= mul7_i_29_reg_2002_pp0_iter6_reg;
        mul7_i_30_reg_2007_pp0_iter2_reg <= mul7_i_30_reg_2007;
        mul7_i_30_reg_2007_pp0_iter3_reg <= mul7_i_30_reg_2007_pp0_iter2_reg;
        mul7_i_30_reg_2007_pp0_iter4_reg <= mul7_i_30_reg_2007_pp0_iter3_reg;
        mul7_i_30_reg_2007_pp0_iter5_reg <= mul7_i_30_reg_2007_pp0_iter4_reg;
        mul7_i_30_reg_2007_pp0_iter6_reg <= mul7_i_30_reg_2007_pp0_iter5_reg;
        mul7_i_30_reg_2007_pp0_iter7_reg <= mul7_i_30_reg_2007_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        mul7_i_2_reg_1622 <= grp_fu_1461_p_dout0;
        mul7_i_3_reg_1627 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        mul7_i_4_reg_1652 <= grp_fu_1461_p_dout0;
        mul7_i_5_reg_1657 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        mul7_i_5_reg_1657_pp0_iter1_reg <= mul7_i_5_reg_1657;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        mul7_i_6_reg_1682 <= grp_fu_1461_p_dout0;
        mul7_i_7_reg_1687 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        mul7_i_6_reg_1682_pp0_iter1_reg <= mul7_i_6_reg_1682;
        mul7_i_7_reg_1687_pp0_iter1_reg <= mul7_i_7_reg_1687;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        mul7_i_8_reg_1712 <= grp_fu_1461_p_dout0;
        mul7_i_9_reg_1717 <= grp_fu_1465_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        mul7_i_8_reg_1712_pp0_iter1_reg <= mul7_i_8_reg_1712;
        mul7_i_9_reg_1717_pp0_iter1_reg <= mul7_i_9_reg_1717;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_684 <= Weights_q1;
        reg_688 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_692 <= grp_fu_1453_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_697 <= grp_fu_1453_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_702 <= grp_fu_1453_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_707 <= grp_fu_1453_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_712 <= grp_fu_1457_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_717 <= grp_fu_1457_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_722 <= grp_fu_1457_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_727 <= grp_fu_1457_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        s_35_reg_2012 <= grp_fu_1453_p_dout0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        OutDense0_ce0 = 1'b1;
    end else begin
        OutDense0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        OutDense0_we0 = 1'b1;
    end else begin
        OutDense0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        Weights_address0 = zext_ln9_fu_1257_p1;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        Weights_address0 = zext_ln7_31_fu_1227_p1;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        Weights_address0 = zext_ln7_29_fu_1197_p1;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        Weights_address0 = zext_ln7_27_fu_1165_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        Weights_address0 = zext_ln7_25_fu_1135_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        Weights_address0 = zext_ln7_23_fu_1105_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        Weights_address0 = zext_ln7_21_fu_1075_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        Weights_address0 = zext_ln7_19_fu_1043_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        Weights_address0 = zext_ln7_17_fu_1013_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        Weights_address0 = zext_ln7_15_fu_983_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        Weights_address0 = zext_ln7_13_fu_953_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        Weights_address0 = zext_ln7_11_fu_921_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        Weights_address0 = zext_ln7_9_fu_891_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        Weights_address0 = zext_ln7_7_fu_861_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Weights_address0 = zext_ln7_5_fu_831_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Weights_address0 = zext_ln7_3_fu_799_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Weights_address0 = zext_ln7_1_fu_774_p1;
    end else begin
        Weights_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage15) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            Weights_address1 = zext_ln7_30_fu_1217_p1;
        end else if (((1'b0 == ap_block_pp0_stage14) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
            Weights_address1 = zext_ln7_28_fu_1185_p1;
        end else if (((1'b0 == ap_block_pp0_stage13) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
            Weights_address1 = zext_ln7_26_fu_1155_p1;
        end else if (((1'b0 == ap_block_pp0_stage12) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            Weights_address1 = zext_ln7_24_fu_1125_p1;
        end else if (((1'b0 == ap_block_pp0_stage11) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
            Weights_address1 = zext_ln7_22_fu_1095_p1;
        end else if (((1'b0 == ap_block_pp0_stage10) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            Weights_address1 = zext_ln7_20_fu_1063_p1;
        end else if (((1'b0 == ap_block_pp0_stage9) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
            Weights_address1 = zext_ln7_18_fu_1033_p1;
        end else if (((1'b0 == ap_block_pp0_stage8) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
            Weights_address1 = zext_ln7_16_fu_1003_p1;
        end else if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            Weights_address1 = zext_ln7_14_fu_973_p1;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            Weights_address1 = zext_ln7_12_fu_941_p1;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            Weights_address1 = zext_ln7_10_fu_911_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            Weights_address1 = zext_ln7_8_fu_881_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            Weights_address1 = zext_ln7_6_fu_851_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            Weights_address1 = zext_ln7_4_fu_819_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            Weights_address1 = zext_ln7_2_fu_789_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            Weights_address1 = zext_ln7_fu_763_p1;
        end else begin
            Weights_address1 = 'bx;
        end
    end else begin
        Weights_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage16_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Weights_ce0 = 1'b1;
    end else begin
        Weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage7_11001) 
    & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        Weights_ce1 = 1'b1;
    end else begin
        Weights_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln3_reg_1497 == 1'd1) & (1'b0 == ap_block_pp0_stage16_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_condition_exit_pp0_iter0_stage16 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage16 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln3_reg_1497_pp0_iter7_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        ap_condition_exit_pp0_iter7_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter7_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2_subdone) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to6 = 1'b1;
    end else begin
        ap_idle_pp0_0to6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to8 = 1'b1;
    end else begin
        ap_idle_pp0_1to8 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage16_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_180;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_662_p0 = reg_707;
    end else if ((((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_662_p0 = reg_702;
    end else if ((((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_662_p0 = reg_697;
    end else if ((((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_662_p0 = reg_692;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_662_p0 = mul7_i_reg_1592;
    end else begin
        grp_fu_662_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_662_p1 = mul7_i_15_reg_1832_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_662_p1 = mul7_i_14_reg_1807_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_662_p1 = mul7_i_13_reg_1802_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_662_p1 = mul7_i_12_reg_1777_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_662_p1 = mul7_i_11_reg_1772_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_662_p1 = mul7_i_10_reg_1747_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_662_p1 = mul7_i_s_reg_1742_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_662_p1 = mul7_i_9_reg_1717_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_662_p1 = mul7_i_8_reg_1712_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_662_p1 = mul7_i_7_reg_1687_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_662_p1 = mul7_i_6_reg_1682_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_662_p1 = mul7_i_5_reg_1657_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_662_p1 = mul7_i_4_reg_1652;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_662_p1 = mul7_i_3_reg_1627;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_662_p1 = mul7_i_2_reg_1622;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_662_p1 = mul7_i_1_reg_1597;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_662_p1 = 32'd0;
    end else begin
        grp_fu_662_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_667_p0 = reg_727;
    end else if ((((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_667_p0 = reg_722;
    end else if ((((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16)) | ((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_667_p0 = reg_717;
    end else if ((((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_667_p0 = reg_712;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_667_p0 = s_35_reg_2012;
    end else begin
        grp_fu_667_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_667_p1 = bitcast_ln9_fu_1262_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_667_p1 = mul7_i_30_reg_2007_pp0_iter7_reg;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_667_p1 = mul7_i_29_reg_2002_pp0_iter7_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_667_p1 = mul7_i_28_reg_1997_pp0_iter7_reg;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_667_p1 = mul7_i_27_reg_1992_pp0_iter6_reg;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_667_p1 = mul7_i_26_reg_1977_pp0_iter6_reg;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_667_p1 = mul7_i_25_reg_1972_pp0_iter6_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_667_p1 = mul7_i_24_reg_1957_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_667_p1 = mul7_i_23_reg_1952_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_667_p1 = mul7_i_22_reg_1927_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_667_p1 = mul7_i_21_reg_1922_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_667_p1 = mul7_i_20_reg_1897_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_667_p1 = mul7_i_19_reg_1892_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_667_p1 = mul7_i_18_reg_1867_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_667_p1 = mul7_i_17_reg_1862_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_667_p1 = mul7_i_16_reg_1837_pp0_iter3_reg;
    end else begin
        grp_fu_667_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_671_p0 = OutGAP4_load_30;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_671_p0 = OutGAP4_load_28;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_671_p0 = OutGAP4_load_26;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_671_p0 = OutGAP4_load_24;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_671_p0 = OutGAP4_load_22;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_671_p0 = OutGAP4_load_20;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_671_p0 = OutGAP4_load_18;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_671_p0 = OutGAP4_load_16;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_671_p0 = OutGAP4_load_14;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_671_p0 = OutGAP4_load_12;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_671_p0 = OutGAP4_load_10;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_671_p0 = OutGAP4_load_8;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_671_p0 = OutGAP4_load_6;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_671_p0 = OutGAP4_load_4;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_671_p0 = OutGAP4_load_2;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_671_p0 = OutGAP4_load;
    end else begin
        grp_fu_671_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_671_p1 = bitcast_ln7_30_fu_1242_p1;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_671_p1 = bitcast_ln7_28_fu_1232_p1;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_671_p1 = bitcast_ln7_26_fu_1202_p1;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_671_p1 = bitcast_ln7_24_fu_1170_p1;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_671_p1 = bitcast_ln7_22_fu_1140_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_671_p1 = bitcast_ln7_20_fu_1110_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_671_p1 = bitcast_ln7_18_fu_1080_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_671_p1 = bitcast_ln7_16_fu_1048_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_671_p1 = bitcast_ln7_14_fu_1018_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_671_p1 = bitcast_ln7_12_fu_988_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_671_p1 = bitcast_ln7_10_fu_958_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_671_p1 = bitcast_ln7_8_fu_926_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_671_p1 = bitcast_ln7_6_fu_896_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_671_p1 = bitcast_ln7_4_fu_866_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_671_p1 = bitcast_ln7_2_fu_836_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_671_p1 = bitcast_ln7_fu_804_p1;
    end else begin
        grp_fu_671_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_675_p0 = OutGAP4_load_31;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_675_p0 = OutGAP4_load_29;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_675_p0 = OutGAP4_load_27;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_675_p0 = OutGAP4_load_25;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_675_p0 = OutGAP4_load_23;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_675_p0 = OutGAP4_load_21;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_675_p0 = OutGAP4_load_19;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_675_p0 = OutGAP4_load_17;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_675_p0 = OutGAP4_load_15;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_675_p0 = OutGAP4_load_13;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_675_p0 = OutGAP4_load_11;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_675_p0 = OutGAP4_load_9;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_675_p0 = OutGAP4_load_7;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_675_p0 = OutGAP4_load_5;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_675_p0 = OutGAP4_load_3;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_675_p0 = OutGAP4_load_1;
    end else begin
        grp_fu_675_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_675_p1 = bitcast_ln7_31_fu_1247_p1;
    end else if (((1'b0 == ap_block_pp0_stage16) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage16))) begin
        grp_fu_675_p1 = bitcast_ln7_29_fu_1237_p1;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        grp_fu_675_p1 = bitcast_ln7_27_fu_1207_p1;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        grp_fu_675_p1 = bitcast_ln7_25_fu_1175_p1;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        grp_fu_675_p1 = bitcast_ln7_23_fu_1145_p1;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        grp_fu_675_p1 = bitcast_ln7_21_fu_1115_p1;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        grp_fu_675_p1 = bitcast_ln7_19_fu_1085_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_675_p1 = bitcast_ln7_17_fu_1053_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_675_p1 = bitcast_ln7_15_fu_1023_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_675_p1 = bitcast_ln7_13_fu_993_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_675_p1 = bitcast_ln7_11_fu_963_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_675_p1 = bitcast_ln7_9_fu_931_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_675_p1 = bitcast_ln7_7_fu_901_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_675_p1 = bitcast_ln7_5_fu_871_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_675_p1 = bitcast_ln7_3_fu_841_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_675_p1 = bitcast_ln7_1_fu_809_p1;
    end else begin
        grp_fu_675_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to8 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter7_stage2) & (ap_idle_pp0_0to6 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_pp0_stage16 : begin
            if ((1'b0 == ap_block_pp0_stage16_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutDense0_address0 = zext_ln3_fu_1266_p1;

assign OutDense0_d0 = ((and_ln9_fu_1306_p2[0:0] == 1'b1) ? 32'd0 : reg_727);

assign add_ln3_fu_747_p2 = (ap_sig_allocacmp_i_2 + 5'd1);

assign add_ln7_10_fu_916_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10520));

assign add_ln7_11_fu_936_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10540));

assign add_ln7_12_fu_968_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10580));

assign add_ln7_13_fu_978_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10600));

assign add_ln7_14_fu_998_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10620));

assign add_ln7_15_fu_1008_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10640));

assign add_ln7_16_fu_1028_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10660));

assign add_ln7_17_fu_1038_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10680));

assign add_ln7_18_fu_1058_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10700));

assign add_ln7_19_fu_1090_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10740));

assign add_ln7_1_fu_768_p2 = ($signed(zext_ln3_1_fu_753_p1) + $signed(14'd10320));

assign add_ln7_20_fu_1100_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10760));

assign add_ln7_21_fu_1120_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10780));

assign add_ln7_22_fu_1130_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10800));

assign add_ln7_23_fu_1150_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10820));

assign add_ln7_24_fu_1160_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10840));

assign add_ln7_25_fu_1180_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10860));

assign add_ln7_26_fu_1212_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10900));

assign add_ln7_27_fu_1222_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10920));

assign add_ln7_2_fu_784_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10340));

assign add_ln7_3_fu_794_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10360));

assign add_ln7_4_fu_814_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10380));

assign add_ln7_5_fu_846_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10420));

assign add_ln7_6_fu_856_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10440));

assign add_ln7_7_fu_876_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10460));

assign add_ln7_8_fu_886_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10480));

assign add_ln7_9_fu_906_p2 = ($signed(zext_ln3_1_reg_1501) + $signed(14'd10500));

assign add_ln7_fu_757_p2 = ($signed(zext_ln3_1_fu_753_p1) + $signed(14'd10300));

assign add_ln9_fu_1252_p2 = ($signed(zext_ln3_1_reg_1501_pp0_iter6_reg) + $signed(14'd10940));

assign and_ln9_fu_1306_p2 = (or_ln9_fu_1300_p2 & grp_fu_1469_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage16 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage16_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage16;

assign bitcast_ln7_10_fu_958_p1 = reg_684;

assign bitcast_ln7_11_fu_963_p1 = reg_688;

assign bitcast_ln7_12_fu_988_p1 = reg_684;

assign bitcast_ln7_13_fu_993_p1 = reg_688;

assign bitcast_ln7_14_fu_1018_p1 = reg_684;

assign bitcast_ln7_15_fu_1023_p1 = reg_688;

assign bitcast_ln7_16_fu_1048_p1 = reg_684;

assign bitcast_ln7_17_fu_1053_p1 = reg_688;

assign bitcast_ln7_18_fu_1080_p1 = reg_684;

assign bitcast_ln7_19_fu_1085_p1 = reg_688;

assign bitcast_ln7_1_fu_809_p1 = reg_688;

assign bitcast_ln7_20_fu_1110_p1 = reg_684;

assign bitcast_ln7_21_fu_1115_p1 = reg_688;

assign bitcast_ln7_22_fu_1140_p1 = reg_684;

assign bitcast_ln7_23_fu_1145_p1 = reg_688;

assign bitcast_ln7_24_fu_1170_p1 = reg_684;

assign bitcast_ln7_25_fu_1175_p1 = reg_688;

assign bitcast_ln7_26_fu_1202_p1 = reg_684;

assign bitcast_ln7_27_fu_1207_p1 = reg_688;

assign bitcast_ln7_28_fu_1232_p1 = reg_684;

assign bitcast_ln7_29_fu_1237_p1 = reg_688;

assign bitcast_ln7_2_fu_836_p1 = reg_684;

assign bitcast_ln7_30_fu_1242_p1 = reg_684;

assign bitcast_ln7_31_fu_1247_p1 = reg_688;

assign bitcast_ln7_3_fu_841_p1 = reg_688;

assign bitcast_ln7_4_fu_866_p1 = reg_684;

assign bitcast_ln7_5_fu_871_p1 = reg_688;

assign bitcast_ln7_6_fu_896_p1 = reg_684;

assign bitcast_ln7_7_fu_901_p1 = reg_688;

assign bitcast_ln7_8_fu_926_p1 = reg_684;

assign bitcast_ln7_9_fu_931_p1 = reg_688;

assign bitcast_ln7_fu_804_p1 = reg_684;

assign bitcast_ln9_1_fu_1270_p1 = reg_727;

assign bitcast_ln9_fu_1262_p1 = Weights_load_52_reg_2022;

assign grp_fu_1453_p_ce = 1'b1;

assign grp_fu_1453_p_din0 = grp_fu_662_p0;

assign grp_fu_1453_p_din1 = grp_fu_662_p1;

assign grp_fu_1453_p_opcode = 2'd0;

assign grp_fu_1457_p_ce = 1'b1;

assign grp_fu_1457_p_din0 = grp_fu_667_p0;

assign grp_fu_1457_p_din1 = grp_fu_667_p1;

assign grp_fu_1457_p_opcode = 2'd0;

assign grp_fu_1461_p_ce = 1'b1;

assign grp_fu_1461_p_din0 = grp_fu_671_p0;

assign grp_fu_1461_p_din1 = grp_fu_671_p1;

assign grp_fu_1465_p_ce = 1'b1;

assign grp_fu_1465_p_din0 = grp_fu_675_p0;

assign grp_fu_1465_p_din1 = grp_fu_675_p1;

assign grp_fu_1469_p_ce = 1'b1;

assign grp_fu_1469_p_din0 = reg_727;

assign grp_fu_1469_p_din1 = 32'd0;

assign grp_fu_1469_p_opcode = 5'd4;

assign icmp_ln3_fu_741_p2 = ((ap_sig_allocacmp_i_2 == 5'd20) ? 1'b1 : 1'b0);

assign icmp_ln9_1_fu_1294_p2 = ((trunc_ln9_fu_1284_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_1288_p2 = ((tmp_s_fu_1274_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln9_fu_1300_p2 = (icmp_ln9_fu_1288_p2 | icmp_ln9_1_fu_1294_p2);

assign tmp_s_fu_1274_p4 = {{bitcast_ln9_1_fu_1270_p1[30:23]}};

assign trunc_ln9_fu_1284_p1 = bitcast_ln9_1_fu_1270_p1[22:0];

assign zext_ln3_1_fu_753_p1 = ap_sig_allocacmp_i_2;

assign zext_ln3_fu_1266_p1 = i_2_reg_1488_pp0_iter8_reg;

assign zext_ln7_10_fu_911_p1 = add_ln7_9_fu_906_p2;

assign zext_ln7_11_fu_921_p1 = add_ln7_10_fu_916_p2;

assign zext_ln7_12_fu_941_p1 = add_ln7_11_fu_936_p2;

assign zext_ln7_13_cast_fu_946_p3 = {{9'd330}, {i_2_reg_1488}};

assign zext_ln7_13_fu_953_p1 = zext_ln7_13_cast_fu_946_p3;

assign zext_ln7_14_fu_973_p1 = add_ln7_12_fu_968_p2;

assign zext_ln7_15_fu_983_p1 = add_ln7_13_fu_978_p2;

assign zext_ln7_16_fu_1003_p1 = add_ln7_14_fu_998_p2;

assign zext_ln7_17_fu_1013_p1 = add_ln7_15_fu_1008_p2;

assign zext_ln7_18_fu_1033_p1 = add_ln7_16_fu_1028_p2;

assign zext_ln7_19_fu_1043_p1 = add_ln7_17_fu_1038_p2;

assign zext_ln7_1_fu_774_p1 = add_ln7_1_fu_768_p2;

assign zext_ln7_20_fu_1063_p1 = add_ln7_18_fu_1058_p2;

assign zext_ln7_21_cast_fu_1068_p3 = {{9'd335}, {i_2_reg_1488}};

assign zext_ln7_21_fu_1075_p1 = zext_ln7_21_cast_fu_1068_p3;

assign zext_ln7_22_fu_1095_p1 = add_ln7_19_fu_1090_p2;

assign zext_ln7_23_fu_1105_p1 = add_ln7_20_fu_1100_p2;

assign zext_ln7_24_fu_1125_p1 = add_ln7_21_fu_1120_p2;

assign zext_ln7_25_fu_1135_p1 = add_ln7_22_fu_1130_p2;

assign zext_ln7_26_fu_1155_p1 = add_ln7_23_fu_1150_p2;

assign zext_ln7_27_fu_1165_p1 = add_ln7_24_fu_1160_p2;

assign zext_ln7_28_fu_1185_p1 = add_ln7_25_fu_1180_p2;

assign zext_ln7_29_cast_fu_1190_p3 = {{9'd340}, {i_2_reg_1488}};

assign zext_ln7_29_fu_1197_p1 = zext_ln7_29_cast_fu_1190_p3;

assign zext_ln7_2_fu_789_p1 = add_ln7_2_fu_784_p2;

assign zext_ln7_30_fu_1217_p1 = add_ln7_26_fu_1212_p2;

assign zext_ln7_31_fu_1227_p1 = add_ln7_27_fu_1222_p2;

assign zext_ln7_3_fu_799_p1 = add_ln7_3_fu_794_p2;

assign zext_ln7_4_fu_819_p1 = add_ln7_4_fu_814_p2;

assign zext_ln7_5_cast_fu_824_p3 = {{9'd325}, {i_2_reg_1488}};

assign zext_ln7_5_fu_831_p1 = zext_ln7_5_cast_fu_824_p3;

assign zext_ln7_6_fu_851_p1 = add_ln7_5_fu_846_p2;

assign zext_ln7_7_fu_861_p1 = add_ln7_6_fu_856_p2;

assign zext_ln7_8_fu_881_p1 = add_ln7_7_fu_876_p2;

assign zext_ln7_9_fu_891_p1 = add_ln7_8_fu_886_p2;

assign zext_ln7_fu_763_p1 = add_ln7_fu_757_p2;

assign zext_ln9_fu_1257_p1 = add_ln9_fu_1252_p2;

always @ (posedge ap_clk) begin
    zext_ln3_1_reg_1501[13:5] <= 9'b000000000;
    zext_ln3_1_reg_1501_pp0_iter1_reg[13:5] <= 9'b000000000;
    zext_ln3_1_reg_1501_pp0_iter2_reg[13:5] <= 9'b000000000;
    zext_ln3_1_reg_1501_pp0_iter3_reg[13:5] <= 9'b000000000;
    zext_ln3_1_reg_1501_pp0_iter4_reg[13:5] <= 9'b000000000;
    zext_ln3_1_reg_1501_pp0_iter5_reg[13:5] <= 9'b000000000;
    zext_ln3_1_reg_1501_pp0_iter6_reg[13:5] <= 9'b000000000;
end

endmodule //CNN_CNN_Pipeline_loop_for_a_Dense_0
