// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_loop_for_3_channel_pad_4_loop_for_channel_pad_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        OutPadConv4_address0,
        OutPadConv4_ce0,
        OutPadConv4_we0,
        OutPadConv4_d0,
        OutPool1_address0,
        OutPool1_ce0,
        OutPool1_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] OutPadConv4_address0;
output   OutPadConv4_ce0;
output   OutPadConv4_we0;
output  [31:0] OutPadConv4_d0;
output  [9:0] OutPool1_address0;
output   OutPool1_ce0;
input  [31:0] OutPool1_q0;

reg ap_idle;
reg OutPadConv4_ce0;
reg OutPadConv4_we0;
reg OutPool1_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln107_fu_114_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] select_ln107_fu_138_p3;
reg   [6:0] select_ln107_reg_316;
reg   [6:0] select_ln107_reg_316_pp0_iter1_reg;
wire   [2:0] empty_138_fu_164_p1;
reg   [2:0] empty_138_reg_328;
reg   [2:0] empty_138_reg_328_pp0_iter1_reg;
wire   [0:0] icmp_ln110_fu_178_p2;
reg   [0:0] icmp_ln110_reg_334;
reg   [0:0] icmp_ln110_reg_334_pp0_iter1_reg;
reg   [0:0] icmp_ln110_reg_334_pp0_iter2_reg;
wire   [0:0] icmp_ln110_1_fu_233_p2;
reg   [0:0] icmp_ln110_1_reg_344;
wire   [63:0] zext_ln110_1_fu_260_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln110_fu_269_p1;
reg   [6:0] n_fu_58;
wire   [6:0] add_ln109_fu_184_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_n_load;
reg   [3:0] c_fu_62;
wire   [3:0] select_ln107_1_fu_152_p3;
reg   [3:0] ap_sig_allocacmp_c_load;
reg   [9:0] indvar_flatten62_fu_66;
wire   [9:0] add_ln107_fu_120_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten62_load;
wire   [0:0] icmp_ln109_fu_132_p2;
wire   [3:0] add_ln107_1_fu_146_p2;
wire   [5:0] tmp_fu_168_p4;
wire   [8:0] p_shl_fu_205_p3;
wire   [6:0] p_shl14_fu_216_p3;
wire   [9:0] p_shl29_cast_fu_212_p1;
wire   [9:0] zext_ln109_fu_223_p1;
wire   [7:0] zext_ln109_2_fu_230_p1;
wire   [7:0] add_ln110_3_fu_244_p2;
wire  signed [9:0] sext_ln110_fu_250_p1;
wire   [9:0] add_ln110_1_fu_238_p2;
wire   [9:0] add_ln110_2_fu_254_p2;
wire   [9:0] grp_fu_282_p3;
wire   [0:0] or_ln110_fu_265_p2;
wire   [3:0] grp_fu_282_p0;
wire   [6:0] grp_fu_282_p1;
wire   [6:0] grp_fu_282_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [9:0] grp_fu_282_p00;
wire   [9:0] grp_fu_282_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 n_fu_58 = 7'd0;
#0 c_fu_62 = 4'd0;
#0 indvar_flatten62_fu_66 = 10'd0;
#0 ap_done_reg = 1'b0;
end

CNN_mac_muladd_4ns_7ns_7ns_10_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 10 ))
mac_muladd_4ns_7ns_7ns_10_4_1_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_282_p0),
    .din1(grp_fu_282_p1),
    .din2(grp_fu_282_p2),
    .ce(1'b1),
    .dout(grp_fu_282_p3)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln107_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_62 <= select_ln107_1_fu_152_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_62 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln107_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten62_fu_66 <= add_ln107_fu_120_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten62_fu_66 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln107_fu_114_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            n_fu_58 <= add_ln109_fu_184_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_58 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_138_reg_328 <= empty_138_fu_164_p1;
        empty_138_reg_328_pp0_iter1_reg <= empty_138_reg_328;
        icmp_ln110_reg_334 <= icmp_ln110_fu_178_p2;
        icmp_ln110_reg_334_pp0_iter1_reg <= icmp_ln110_reg_334;
        select_ln107_reg_316 <= select_ln107_fu_138_p3;
        select_ln107_reg_316_pp0_iter1_reg <= select_ln107_reg_316;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln110_1_reg_344 <= icmp_ln110_1_fu_233_p2;
        icmp_ln110_reg_334_pp0_iter2_reg <= icmp_ln110_reg_334_pp0_iter1_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        OutPadConv4_ce0 = 1'b1;
    end else begin
        OutPadConv4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        OutPadConv4_we0 = 1'b1;
    end else begin
        OutPadConv4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        OutPool1_ce0 = 1'b1;
    end else begin
        OutPool1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln107_fu_114_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_c_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_62;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten62_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten62_load = indvar_flatten62_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_n_load = 7'd0;
    end else begin
        ap_sig_allocacmp_n_load = n_fu_58;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutPadConv4_address0 = zext_ln110_fu_269_p1;

assign OutPadConv4_d0 = ((or_ln110_fu_265_p2[0:0] == 1'b1) ? 32'd0 : OutPool1_q0);

assign OutPool1_address0 = zext_ln110_1_fu_260_p1;

assign add_ln107_1_fu_146_p2 = (ap_sig_allocacmp_c_load + 4'd1);

assign add_ln107_fu_120_p2 = (ap_sig_allocacmp_indvar_flatten62_load + 10'd1);

assign add_ln109_fu_184_p2 = (select_ln107_fu_138_p3 + 7'd1);

assign add_ln110_1_fu_238_p2 = (p_shl29_cast_fu_212_p1 + zext_ln109_fu_223_p1);

assign add_ln110_2_fu_254_p2 = ($signed(sext_ln110_fu_250_p1) + $signed(add_ln110_1_fu_238_p2));

assign add_ln110_3_fu_244_p2 = ($signed(zext_ln109_2_fu_230_p1) + $signed(8'd254));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_138_fu_164_p1 = select_ln107_1_fu_152_p3[2:0];

assign grp_fu_282_p0 = grp_fu_282_p00;

assign grp_fu_282_p00 = select_ln107_1_fu_152_p3;

assign grp_fu_282_p1 = 10'd84;

assign grp_fu_282_p2 = grp_fu_282_p20;

assign grp_fu_282_p20 = select_ln107_reg_316_pp0_iter1_reg;

assign icmp_ln107_fu_114_p2 = ((ap_sig_allocacmp_indvar_flatten62_load == 10'd672) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_132_p2 = ((ap_sig_allocacmp_n_load == 7'd84) ? 1'b1 : 1'b0);

assign icmp_ln110_1_fu_233_p2 = ((select_ln107_reg_316_pp0_iter1_reg > 7'd81) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_178_p2 = ((tmp_fu_168_p4 == 6'd0) ? 1'b1 : 1'b0);

assign or_ln110_fu_265_p2 = (icmp_ln110_reg_334_pp0_iter2_reg | icmp_ln110_1_reg_344);

assign p_shl14_fu_216_p3 = {{empty_138_reg_328_pp0_iter1_reg}, {4'd0}};

assign p_shl29_cast_fu_212_p1 = p_shl_fu_205_p3;

assign p_shl_fu_205_p3 = {{empty_138_reg_328_pp0_iter1_reg}, {6'd0}};

assign select_ln107_1_fu_152_p3 = ((icmp_ln109_fu_132_p2[0:0] == 1'b1) ? add_ln107_1_fu_146_p2 : ap_sig_allocacmp_c_load);

assign select_ln107_fu_138_p3 = ((icmp_ln109_fu_132_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_n_load);

assign sext_ln110_fu_250_p1 = $signed(add_ln110_3_fu_244_p2);

assign tmp_fu_168_p4 = {{select_ln107_fu_138_p3[6:1]}};

assign zext_ln109_2_fu_230_p1 = select_ln107_reg_316_pp0_iter1_reg;

assign zext_ln109_fu_223_p1 = p_shl14_fu_216_p3;

assign zext_ln110_1_fu_260_p1 = add_ln110_2_fu_254_p2;

assign zext_ln110_fu_269_p1 = grp_fu_282_p3;

endmodule //CNN_CNN_Pipeline_loop_for_3_channel_pad_4_loop_for_channel_pad_4
