// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module CNN_CNN_Pipeline_VITIS_LOOP_195_1_loop_for_ap_7_loop_for_fc_7_loop_for_fa_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Weights_address0,
        Weights_ce0,
        Weights_q0,
        Weights_address1,
        Weights_ce1,
        Weights_q1,
        OutPadConv7_address0,
        OutPadConv7_ce0,
        OutPadConv7_q0,
        OutConv7_address0,
        OutConv7_ce0,
        OutConv7_we0,
        OutConv7_d0,
        grp_fu_1453_p_din0,
        grp_fu_1453_p_din1,
        grp_fu_1453_p_opcode,
        grp_fu_1453_p_dout0,
        grp_fu_1453_p_ce,
        grp_fu_1461_p_din0,
        grp_fu_1461_p_din1,
        grp_fu_1461_p_dout0,
        grp_fu_1461_p_ce,
        grp_fu_1469_p_din0,
        grp_fu_1469_p_din1,
        grp_fu_1469_p_opcode,
        grp_fu_1469_p_dout0,
        grp_fu_1469_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] Weights_address0;
output   Weights_ce0;
input  [31:0] Weights_q0;
output  [13:0] Weights_address1;
output   Weights_ce1;
input  [31:0] Weights_q1;
output  [10:0] OutPadConv7_address0;
output   OutPadConv7_ce0;
input  [31:0] OutPadConv7_q0;
output  [10:0] OutConv7_address0;
output   OutConv7_ce0;
output   OutConv7_we0;
output  [31:0] OutConv7_d0;
output  [31:0] grp_fu_1453_p_din0;
output  [31:0] grp_fu_1453_p_din1;
output  [1:0] grp_fu_1453_p_opcode;
input  [31:0] grp_fu_1453_p_dout0;
output   grp_fu_1453_p_ce;
output  [31:0] grp_fu_1461_p_din0;
output  [31:0] grp_fu_1461_p_din1;
input  [31:0] grp_fu_1461_p_dout0;
output   grp_fu_1461_p_ce;
output  [31:0] grp_fu_1469_p_din0;
output  [31:0] grp_fu_1469_p_din1;
output  [4:0] grp_fu_1469_p_opcode;
input  [0:0] grp_fu_1469_p_dout0;
output   grp_fu_1469_p_ce;

reg ap_idle;
reg Weights_ce0;
reg Weights_ce1;
reg OutPadConv7_ce0;
reg OutConv7_ce0;
reg OutConv7_we0;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_subdone;
reg   [0:0] icmp_ln195_reg_796;
reg    ap_condition_exit_pp0_iter0_stage3;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [8:0] indvar_flatten196_load_reg_786;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [13:0] indvar_flatten211_load_reg_791;
wire   [0:0] icmp_ln195_fu_239_p2;
wire   [0:0] icmp_ln197_fu_263_p2;
reg   [0:0] icmp_ln197_reg_800;
wire   [5:0] select_ln195_1_fu_307_p3;
reg   [5:0] select_ln195_1_reg_805;
reg   [5:0] select_ln195_1_reg_805_pp0_iter1_reg;
wire   [0:0] or_ln197_fu_321_p2;
reg   [0:0] or_ln197_reg_810;
reg   [0:0] or_ln197_reg_810_pp0_iter1_reg;
wire   [5:0] add_ln203_6_fu_524_p2;
reg   [5:0] add_ln203_6_reg_826;
wire   [0:0] icmp_ln202_1_fu_536_p2;
reg   [0:0] icmp_ln202_1_reg_831;
reg   [0:0] icmp_ln202_1_reg_831_pp0_iter1_reg;
reg   [0:0] icmp_ln202_1_reg_831_pp0_iter2_reg;
reg   [0:0] icmp_ln202_1_reg_831_pp0_iter3_reg;
reg   [0:0] icmp_ln202_1_reg_831_pp0_iter4_reg;
wire   [0:0] icmp_ln200_1_fu_542_p2;
reg   [0:0] icmp_ln200_1_reg_835;
reg   [0:0] icmp_ln200_1_reg_835_pp0_iter1_reg;
reg   [0:0] icmp_ln200_1_reg_835_pp0_iter2_reg;
reg   [0:0] icmp_ln200_1_reg_835_pp0_iter3_reg;
reg   [0:0] icmp_ln200_1_reg_835_pp0_iter4_reg;
wire   [10:0] add_ln205_fu_558_p2;
reg   [10:0] add_ln205_reg_839;
reg   [10:0] add_ln205_reg_839_pp0_iter1_reg;
reg   [10:0] add_ln205_reg_839_pp0_iter2_reg;
reg   [10:0] add_ln205_reg_839_pp0_iter3_reg;
reg   [10:0] add_ln205_reg_839_pp0_iter4_reg;
reg   [31:0] Weights_load_88_reg_844;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_pp0_stage3_11001;
reg   [31:0] OutPadConv7_load_reg_859;
wire   [31:0] bitcast_ln203_fu_630_p1;
reg   [31:0] mul21_i7_reg_869;
wire   [31:0] select_ln197_1_fu_637_p3;
reg   [31:0] Weights_load_reg_884;
reg   [31:0] s_reg_889;
wire   [31:0] empty_147_fu_664_p1;
reg   [31:0] add28_i7_reg_899;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln203_3_fu_519_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln203_5_fu_592_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] arrayidx51_sum_cast_fu_654_p1;
wire   [63:0] zext_ln205_1_fu_709_p1;
wire    ap_block_pp0_stage3;
reg   [31:0] s_130_fu_94;
wire    ap_loop_init;
reg   [2:0] j_fu_98;
wire   [2:0] add_ln202_fu_530_p2;
reg   [5:0] k_fu_102;
wire   [5:0] select_ln200_fu_393_p3;
reg   [8:0] indvar_flatten196_fu_106;
wire   [8:0] select_ln200_1_fu_601_p3;
reg   [5:0] y_fu_110;
wire   [5:0] select_ln197_2_fu_359_p3;
reg   [13:0] indvar_flatten211_fu_114;
wire   [13:0] select_ln197_3_fu_613_p3;
reg   [5:0] n_fu_118;
reg   [17:0] indvar_flatten235_fu_122;
wire   [17:0] add_ln195_fu_245_p2;
reg   [31:0] grp_fu_177_p0;
reg   [31:0] grp_fu_177_p1;
wire    ap_block_pp0_stage2;
wire   [0:0] icmp_ln200_fu_289_p2;
wire   [0:0] xor_ln195_fu_277_p2;
wire   [5:0] add_ln195_1_fu_301_p2;
wire   [5:0] select_ln195_fu_269_p3;
wire   [0:0] and_ln195_1_fu_295_p2;
wire   [0:0] xor_ln197_fu_335_p2;
wire   [0:0] icmp_ln202_fu_283_p2;
wire   [0:0] and_ln195_fu_347_p2;
wire   [0:0] or_ln197_1_fu_341_p2;
wire   [5:0] add_ln197_fu_315_p2;
wire   [5:0] select_ln197_fu_327_p3;
wire   [0:0] and_ln197_fu_353_p2;
wire   [0:0] or_ln198_fu_373_p2;
wire   [0:0] or_ln198_1_fu_379_p2;
wire   [5:0] add_ln200_fu_367_p2;
wire   [4:0] empty_fu_401_p1;
wire   [11:0] p_shl_fu_405_p3;
wire   [9:0] p_shl15_fu_417_p3;
wire   [7:0] p_shl16_fu_429_p3;
wire   [4:0] empty_148_fu_453_p1;
wire   [6:0] p_shl17_fu_457_p3;
wire   [2:0] select_ln198_fu_385_p3;
wire   [9:0] zext_ln200_fu_445_p1;
wire   [9:0] add_ln203_fu_477_p2;
wire   [12:0] zext_ln203_fu_483_p1;
wire   [12:0] p_shl55_cast_fu_413_p1;
wire   [12:0] add_ln203_2_fu_487_p2;
wire   [12:0] zext_ln202_2_fu_473_p1;
wire   [12:0] add_ln203_4_fu_497_p2;
wire   [12:0] p_shl57_cast_fu_465_p1;
wire   [12:0] add_ln203_5_fu_503_p2;
wire   [13:0] zext_ln203_2_fu_509_p1;
wire   [13:0] zext_ln203_1_fu_493_p1;
wire   [13:0] add_ln203_1_fu_513_p2;
wire   [5:0] zext_ln202_1_fu_469_p1;
wire   [8:0] zext_ln197_fu_437_p1;
wire   [8:0] zext_ln197_1_fu_441_p1;
wire   [8:0] add_ln205_1_fu_548_p2;
wire   [10:0] zext_ln205_fu_554_p1;
wire   [10:0] p_shl56_cast_fu_425_p1;
wire   [10:0] grp_fu_721_p3;
wire   [8:0] add_ln200_1_fu_596_p2;
wire   [13:0] add_ln197_1_fu_608_p2;
wire   [13:0] zext_ln195_fu_645_p1;
wire   [13:0] arrayidx51_sum_fu_648_p2;
wire   [31:0] bitcast_ln205_fu_668_p1;
wire   [7:0] tmp_s_fu_671_p4;
wire   [22:0] trunc_ln205_fu_681_p1;
wire   [0:0] icmp_ln205_1_fu_691_p2;
wire   [0:0] icmp_ln205_fu_685_p2;
wire   [0:0] or_ln205_fu_697_p2;
wire   [0:0] and_ln205_fu_703_p2;
wire   [5:0] grp_fu_721_p0;
wire   [5:0] grp_fu_721_p1;
wire   [5:0] grp_fu_721_p2;
wire    ap_block_pp0_stage2_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [3:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to4;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage1_00001;
wire   [10:0] grp_fu_721_p00;
wire   [10:0] grp_fu_721_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 s_130_fu_94 = 32'd0;
#0 j_fu_98 = 3'd0;
#0 k_fu_102 = 6'd0;
#0 indvar_flatten196_fu_106 = 9'd0;
#0 y_fu_110 = 6'd0;
#0 indvar_flatten211_fu_114 = 14'd0;
#0 n_fu_118 = 6'd0;
#0 indvar_flatten235_fu_122 = 18'd0;
#0 ap_done_reg = 1'b0;
end

CNN_mac_muladd_6ns_6ns_6ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 6 ),
    .dout_WIDTH( 11 ))
mac_muladd_6ns_6ns_6ns_11_4_1_U100(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_721_p0),
    .din1(grp_fu_721_p1),
    .din2(grp_fu_721_p2),
    .ce(1'b1),
    .dout(grp_fu_721_p3)
);

CNN_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage3),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage3)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten196_fu_106 <= 9'd0;
        end else if (((icmp_ln195_reg_796 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten196_fu_106 <= select_ln200_1_fu_601_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten211_fu_114 <= 14'd0;
        end else if (((icmp_ln195_reg_796 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten211_fu_114 <= select_ln197_3_fu_613_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten235_fu_122 <= 18'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln195_fu_239_p2 == 1'd0))) begin
        indvar_flatten235_fu_122 <= add_ln195_fu_245_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        j_fu_98 <= 3'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln195_fu_239_p2 == 1'd0))) begin
        j_fu_98 <= add_ln202_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_fu_102 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln195_fu_239_p2 == 1'd0))) begin
        k_fu_102 <= select_ln200_fu_393_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        n_fu_118 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln195_fu_239_p2 == 1'd0))) begin
        n_fu_118 <= select_ln195_1_fu_307_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            s_130_fu_94 <= 32'd0;
        end else if ((ap_enable_reg_pp0_iter3 == 1'b1)) begin
            s_130_fu_94 <= grp_fu_1453_p_dout0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_fu_110 <= 6'd0;
    end else if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln195_fu_239_p2 == 1'd0))) begin
        y_fu_110 <= select_ln197_2_fu_359_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        OutPadConv7_load_reg_859 <= OutPadConv7_q0;
        add_ln203_6_reg_826 <= add_ln203_6_fu_524_p2;
        add_ln205_reg_839 <= add_ln205_fu_558_p2;
        add_ln205_reg_839_pp0_iter1_reg <= add_ln205_reg_839;
        add_ln205_reg_839_pp0_iter2_reg <= add_ln205_reg_839_pp0_iter1_reg;
        add_ln205_reg_839_pp0_iter3_reg <= add_ln205_reg_839_pp0_iter2_reg;
        add_ln205_reg_839_pp0_iter4_reg <= add_ln205_reg_839_pp0_iter3_reg;
        icmp_ln195_reg_796 <= icmp_ln195_fu_239_p2;
        icmp_ln197_reg_800 <= icmp_ln197_fu_263_p2;
        icmp_ln200_1_reg_835 <= icmp_ln200_1_fu_542_p2;
        icmp_ln200_1_reg_835_pp0_iter1_reg <= icmp_ln200_1_reg_835;
        icmp_ln200_1_reg_835_pp0_iter2_reg <= icmp_ln200_1_reg_835_pp0_iter1_reg;
        icmp_ln200_1_reg_835_pp0_iter3_reg <= icmp_ln200_1_reg_835_pp0_iter2_reg;
        icmp_ln200_1_reg_835_pp0_iter4_reg <= icmp_ln200_1_reg_835_pp0_iter3_reg;
        icmp_ln202_1_reg_831 <= icmp_ln202_1_fu_536_p2;
        icmp_ln202_1_reg_831_pp0_iter1_reg <= icmp_ln202_1_reg_831;
        icmp_ln202_1_reg_831_pp0_iter2_reg <= icmp_ln202_1_reg_831_pp0_iter1_reg;
        icmp_ln202_1_reg_831_pp0_iter3_reg <= icmp_ln202_1_reg_831_pp0_iter2_reg;
        icmp_ln202_1_reg_831_pp0_iter4_reg <= icmp_ln202_1_reg_831_pp0_iter3_reg;
        indvar_flatten196_load_reg_786 <= indvar_flatten196_fu_106;
        indvar_flatten211_load_reg_791 <= indvar_flatten211_fu_114;
        or_ln197_reg_810 <= or_ln197_fu_321_p2;
        or_ln197_reg_810_pp0_iter1_reg <= or_ln197_reg_810;
        select_ln195_1_reg_805 <= select_ln195_1_fu_307_p3;
        select_ln195_1_reg_805_pp0_iter1_reg <= select_ln195_1_reg_805;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Weights_load_88_reg_844 <= Weights_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        Weights_load_reg_884 <= Weights_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add28_i7_reg_899 <= grp_fu_1453_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul21_i7_reg_869 <= grp_fu_1461_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_reg_889 <= grp_fu_1453_p_dout0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        OutConv7_ce0 = 1'b1;
    end else begin
        OutConv7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (icmp_ln200_1_reg_835_pp0_iter4_reg == 1'd1) & (icmp_ln202_1_reg_831_pp0_iter4_reg == 1'd1))) begin
        OutConv7_we0 = 1'b1;
    end else begin
        OutConv7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        OutPadConv7_ce0 = 1'b1;
    end else begin
        OutPadConv7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Weights_ce0 = 1'b1;
    end else begin
        Weights_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        Weights_ce1 = 1'b1;
    end else begin
        Weights_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln195_reg_796 == 1'd1) & (1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to4 = 1'b1;
    end else begin
        ap_idle_pp0_1to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_177_p0 = s_reg_889;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_177_p0 = select_ln197_1_fu_637_p3;
    end else begin
        grp_fu_177_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_177_p1 = empty_147_fu_664_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_177_p1 = mul21_i7_reg_869;
    end else begin
        grp_fu_177_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to4 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OutConv7_address0 = zext_ln205_1_fu_709_p1;

assign OutConv7_d0 = ((and_ln205_fu_703_p2[0:0] == 1'b1) ? 32'd0 : add28_i7_reg_899);

assign OutPadConv7_address0 = zext_ln203_5_fu_592_p1;

assign Weights_address0 = arrayidx51_sum_cast_fu_654_p1;

assign Weights_address1 = zext_ln203_3_fu_519_p1;

assign add_ln195_1_fu_301_p2 = (n_fu_118 + 6'd1);

assign add_ln195_fu_245_p2 = (indvar_flatten235_fu_122 + 18'd1);

assign add_ln197_1_fu_608_p2 = (indvar_flatten211_load_reg_791 + 14'd1);

assign add_ln197_fu_315_p2 = (select_ln195_fu_269_p3 + 6'd1);

assign add_ln200_1_fu_596_p2 = (indvar_flatten196_load_reg_786 + 9'd1);

assign add_ln200_fu_367_p2 = (select_ln197_fu_327_p3 + 6'd1);

assign add_ln202_fu_530_p2 = (select_ln198_fu_385_p3 + 3'd1);

assign add_ln203_1_fu_513_p2 = (zext_ln203_2_fu_509_p1 + zext_ln203_1_fu_493_p1);

assign add_ln203_2_fu_487_p2 = (zext_ln203_fu_483_p1 + p_shl55_cast_fu_413_p1);

assign add_ln203_4_fu_497_p2 = ($signed(zext_ln202_2_fu_473_p1) + $signed(13'd5148));

assign add_ln203_5_fu_503_p2 = (add_ln203_4_fu_497_p2 + p_shl57_cast_fu_465_p1);

assign add_ln203_6_fu_524_p2 = (select_ln197_2_fu_359_p3 + zext_ln202_1_fu_469_p1);

assign add_ln203_fu_477_p2 = (p_shl15_fu_417_p3 + zext_ln200_fu_445_p1);

assign add_ln205_1_fu_548_p2 = (zext_ln197_fu_437_p1 + zext_ln197_1_fu_441_p1);

assign add_ln205_fu_558_p2 = (zext_ln205_fu_554_p1 + p_shl56_cast_fu_425_p1);

assign and_ln195_1_fu_295_p2 = (xor_ln195_fu_277_p2 & icmp_ln200_fu_289_p2);

assign and_ln195_fu_347_p2 = (xor_ln195_fu_277_p2 & icmp_ln202_fu_283_p2);

assign and_ln197_fu_353_p2 = (or_ln197_1_fu_341_p2 & and_ln195_fu_347_p2);

assign and_ln205_fu_703_p2 = (or_ln205_fu_697_p2 & grp_fu_1469_p_dout0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage3;

assign arrayidx51_sum_cast_fu_654_p1 = arrayidx51_sum_fu_648_p2;

assign arrayidx51_sum_fu_648_p2 = ($signed(zext_ln195_fu_645_p1) + $signed(14'd10268));

assign bitcast_ln203_fu_630_p1 = Weights_load_88_reg_844;

assign bitcast_ln205_fu_668_p1 = add28_i7_reg_899;

assign empty_147_fu_664_p1 = Weights_load_reg_884;

assign empty_148_fu_453_p1 = select_ln200_fu_393_p3[4:0];

assign empty_fu_401_p1 = select_ln195_1_fu_307_p3[4:0];

assign grp_fu_1453_p_ce = 1'b1;

assign grp_fu_1453_p_din0 = grp_fu_177_p0;

assign grp_fu_1453_p_din1 = grp_fu_177_p1;

assign grp_fu_1453_p_opcode = 2'd0;

assign grp_fu_1461_p_ce = 1'b1;

assign grp_fu_1461_p_din0 = bitcast_ln203_fu_630_p1;

assign grp_fu_1461_p_din1 = OutPadConv7_load_reg_859;

assign grp_fu_1469_p_ce = 1'b1;

assign grp_fu_1469_p_din0 = add28_i7_reg_899;

assign grp_fu_1469_p_din1 = 32'd0;

assign grp_fu_1469_p_opcode = 5'd4;

assign grp_fu_721_p0 = grp_fu_721_p00;

assign grp_fu_721_p00 = select_ln200_fu_393_p3;

assign grp_fu_721_p1 = 11'd44;

assign grp_fu_721_p2 = grp_fu_721_p20;

assign grp_fu_721_p20 = add_ln203_6_reg_826;

assign icmp_ln195_fu_239_p2 = ((indvar_flatten235_fu_122 == 18'd204800) ? 1'b1 : 1'b0);

assign icmp_ln197_fu_263_p2 = ((indvar_flatten211_fu_114 == 14'd6400) ? 1'b1 : 1'b0);

assign icmp_ln200_1_fu_542_p2 = ((select_ln200_fu_393_p3 == 6'd31) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_289_p2 = ((indvar_flatten196_fu_106 == 9'd160) ? 1'b1 : 1'b0);

assign icmp_ln202_1_fu_536_p2 = ((add_ln202_fu_530_p2 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln202_fu_283_p2 = ((j_fu_98 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln205_1_fu_691_p2 = ((trunc_ln205_fu_681_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln205_fu_685_p2 = ((tmp_s_fu_671_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln197_1_fu_341_p2 = (xor_ln197_fu_335_p2 | icmp_ln197_fu_263_p2);

assign or_ln197_fu_321_p2 = (icmp_ln197_fu_263_p2 | and_ln195_1_fu_295_p2);

assign or_ln198_1_fu_379_p2 = (or_ln198_fu_373_p2 | icmp_ln197_fu_263_p2);

assign or_ln198_fu_373_p2 = (and_ln197_fu_353_p2 | and_ln195_1_fu_295_p2);

assign or_ln205_fu_697_p2 = (icmp_ln205_fu_685_p2 | icmp_ln205_1_fu_691_p2);

assign p_shl15_fu_417_p3 = {{empty_fu_401_p1}, {5'd0}};

assign p_shl16_fu_429_p3 = {{empty_fu_401_p1}, {3'd0}};

assign p_shl17_fu_457_p3 = {{empty_148_fu_453_p1}, {2'd0}};

assign p_shl55_cast_fu_413_p1 = p_shl_fu_405_p3;

assign p_shl56_cast_fu_425_p1 = p_shl15_fu_417_p3;

assign p_shl57_cast_fu_465_p1 = p_shl17_fu_457_p3;

assign p_shl_fu_405_p3 = {{empty_fu_401_p1}, {7'd0}};

assign select_ln195_1_fu_307_p3 = ((icmp_ln197_fu_263_p2[0:0] == 1'b1) ? add_ln195_1_fu_301_p2 : n_fu_118);

assign select_ln195_fu_269_p3 = ((icmp_ln197_fu_263_p2[0:0] == 1'b1) ? 6'd0 : y_fu_110);

assign select_ln197_1_fu_637_p3 = ((or_ln197_reg_810_pp0_iter1_reg[0:0] == 1'b1) ? 32'd0 : s_130_fu_94);

assign select_ln197_2_fu_359_p3 = ((and_ln195_1_fu_295_p2[0:0] == 1'b1) ? add_ln197_fu_315_p2 : select_ln195_fu_269_p3);

assign select_ln197_3_fu_613_p3 = ((icmp_ln197_reg_800[0:0] == 1'b1) ? 14'd1 : add_ln197_1_fu_608_p2);

assign select_ln197_fu_327_p3 = ((or_ln197_fu_321_p2[0:0] == 1'b1) ? 6'd0 : k_fu_102);

assign select_ln198_fu_385_p3 = ((or_ln198_1_fu_379_p2[0:0] == 1'b1) ? 3'd0 : j_fu_98);

assign select_ln200_1_fu_601_p3 = ((or_ln197_reg_810[0:0] == 1'b1) ? 9'd1 : add_ln200_1_fu_596_p2);

assign select_ln200_fu_393_p3 = ((and_ln197_fu_353_p2[0:0] == 1'b1) ? add_ln200_fu_367_p2 : select_ln197_fu_327_p3);

assign tmp_s_fu_671_p4 = {{bitcast_ln205_fu_668_p1[30:23]}};

assign trunc_ln205_fu_681_p1 = bitcast_ln205_fu_668_p1[22:0];

assign xor_ln195_fu_277_p2 = (icmp_ln197_fu_263_p2 ^ 1'd1);

assign xor_ln197_fu_335_p2 = (icmp_ln200_fu_289_p2 ^ 1'd1);

assign zext_ln195_fu_645_p1 = select_ln195_1_reg_805_pp0_iter1_reg;

assign zext_ln197_1_fu_441_p1 = select_ln197_2_fu_359_p3;

assign zext_ln197_fu_437_p1 = p_shl16_fu_429_p3;

assign zext_ln200_fu_445_p1 = select_ln200_fu_393_p3;

assign zext_ln202_1_fu_469_p1 = select_ln198_fu_385_p3;

assign zext_ln202_2_fu_473_p1 = select_ln198_fu_385_p3;

assign zext_ln203_1_fu_493_p1 = add_ln203_2_fu_487_p2;

assign zext_ln203_2_fu_509_p1 = add_ln203_5_fu_503_p2;

assign zext_ln203_3_fu_519_p1 = add_ln203_1_fu_513_p2;

assign zext_ln203_5_fu_592_p1 = grp_fu_721_p3;

assign zext_ln203_fu_483_p1 = add_ln203_fu_477_p2;

assign zext_ln205_1_fu_709_p1 = add_ln205_reg_839_pp0_iter4_reg;

assign zext_ln205_fu_554_p1 = add_ln205_1_fu_548_p2;

endmodule //CNN_CNN_Pipeline_VITIS_LOOP_195_1_loop_for_ap_7_loop_for_fc_7_loop_for_fa_7
